#!/bin/bash
DIR=$(dirname "$0")
clear
cd $DIR
ARCH=$(arch)

PACKAGEROOT=package-root
PRIMESDK=Applications/CASIO
SHARED=$PACKAGEROOT/Users/Shared
NAME=PrizmSDK
IDENTIFIER=uk.insoft.$NAME

IDENTITY=security find-identity -v -p basic | awk -F'"' '/Developer ID Installer:/ {print $2}'
APPLE_ID="richie_uk@icloud.com"
TEAM_ID="8XN79M4JCJ"
PASSWORD="bljo-uqdx-niju-qmwp"

pkgbuild --root package-root \
         --identifier $IDENTIFIER \
         --version 1.0 --install-location / \
         --scripts scripts \
         $NAME.pkg
         
productsign --sign "Developer ID Installer: Richard Hughes (8XN79M4JCJ)" $NAME.pkg $NAME-signed.pkg

#xcrun notarytool submit --apple-id $APPLE_ID \
#                        --password $PASSWORD \
#                        --team-id $TEAM_ID \
#                        --wait $NAME-signed.pkg
                        
read -p "Press Enter to continue."

./update_distribution.sh
productbuild --distribution distribution.xml \
             --resources resources \
             --package-path $NAME-signed.pkg \
             $NAME-installer.pkg
             
             
productsign --sign "Developer ID Installer: Richard Hughes (8XN79M4JCJ)" $NAME-installer.pkg $NAME-installer-signed.pkg
#pkgutil --check-signature $NAME-installer-signed.pkg

#xcrun notarytool submit --apple-id $APPLE_ID \
#                        --password $PASSWORD \
#                        --team-id $TEAM_ID \
#                        --wait $NAME-installer-signed.pkg

read -p "Press Enter to continue."

rm -rf $NAME.pkg
rm -rf $NAME-signed.pkg
rm -rf $NAME-installer.pkg

spctl -a -v $NAME-installer-signed.pkg
 
read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
