#!/bin/bash

# MIT License
# 
# Copyright (c) 2025 Insoft
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

grep -qxF 'export PATH=/Applications/CASIO/PrizmSDK:/Applications/CASIO/PrizmSDK/bin:/Applications/CASIO/PrizmSDK/sh3eb-elf/bin:$PATH' ~/.zshrc || echo 'export PATH=/Applications/CASIO/PrizmSDK:/Applications/CASIO/PrizmSDK/bin:/Applications/CASIO/PrizmSDK/sh3eb-elf/bin:$PATH' >> ~/.zshrc
grep -qxF 'export FXCGSDK=/Applications/CASIO/PrizmSDK' ~/.zshrc || echo 'export FXCGSDK=/Applications/CASIO/PrizmSDK' >> ~/.zshrc
source ~/.zshrc

# Detect the currently logged-in user (excluding root)
CURRENT_USER=$(stat -f%Su /dev/console)

# Define the target home directory
USER_HOME="/Users/$CURRENT_USER"

cp -R /private/tmp/PrizmSDK/Prizm "$USER_HOME/Documents"
rm -r /private/tmp/PrizmSDK
chown -R "$CURRENT_USER" "$USER_HOME/Documents/Prizm"
chgrp -R staff "$USER_HOME/Documents/Prizm"

find /Applications/CASIO/PrizmSDK/bin -type f -exec codesign --remove-signature {} \;
find /Applications/CASIO/PrizmSDK/sh3eb-elf/bin -type f -exec codesign --remove-signature {} \;
find /Applications/CASIO/PrizmSDK/libexec/gcc/sh3eb-elf -type f -exec codesign --remove-signature {} \;
find /Applications/CASIO/PrizmSDK/lib -type f -exec codesign --remove-signature {} \;


exit 0
